spring:
  application:
    name: activiti-learning
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti_learning?useUnicode=true&characterEncoding=utf8
    username: root
    password: felix19920320
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
  activiti:
    check-process-definitions: false
  mvc:
    static-path-pattern: /**
security:
  basic:
    enabled: false
server:
  port: 6000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaoantimes.taichi.entity

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.xiaoantimes.taichi.entity
  global-config:
    id-type: 2
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false